### ISSUE TITLE
If you have an non-remapped version in your local maven repo, the remapped one is not created

### ISSUE THREAD

**Issue by SpraxDev** [SpraxDev/Action-SpigotMC#139]
```yaml
      - name: Compile Spigot versions
        uses: SpraxDev/Action-SpigotMC@v4
        with:
          versions: 1.19
          remapped: false

      - name: Compile Spigot versions
        uses: SpraxDev/Action-SpigotMC@v4
        with:
          versions: 1.19
          remapped: true
```

The second call is skipped because it found the non-remapped version.
