### ISSUE TITLE
Output Directory Option

### ISSUE THREAD

**Issue by JakeGBLP** [SpraxDev/Action-SpigotMC#201]
**Is your feature request related to a problem? Please describe.**
Having access to where the output is placed would be nice, this way one could use this action to get the spigot server jar and boot up a server within the action.

**Describe the solution you'd like**
An option like "outputDirectory"

**Additional context**
The messages around this one https://discord.com/channels/344982818863972352/718492339693289532/1334125094787743764

**Comment by SpraxDev** [comment]
@JakeGBLP , if you have time, could you please try the `dev` branch and setting the `finalJarOutputDir` input option?

Something like this:
```yaml
- uses: SpraxDev/Action-SpigotMC@dev
  with:
    finalJarOutputDir: path-to-a-directory/
```

And let me know if it works or you have any more feedback etc.
