### ISSUE TITLE
Error: Unable to resolve action `SpraxDev/Action-Spigot@v1`, repository not found

### ISSUE THREAD

**Issue by JorelAli** [SpraxDev/Action-SpigotMC#21]
* **Action Version**: v1
* **Action Configuration**: 

```yml
  
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    
    - name: Download a tonne of spigot
      uses: SpraxDev/Action-Spigot@v1
      with:
        versions: 1.13, 1.13.1, 1.13.2, 1.14, 1.14.3, 1.14.4, 1.15, 1.16.1, 1.16.2, 1.16.4
        target: Spigot
        generateSrc: false
        generateDoc: false
        disableJavaCheck: false
        forceRun: false
        threads: -1

    # Runs a set of commands using the runners shell
    #- name: Run a multi-line script
    #  run: |
    #    chmod u+x downloadSpigot.sh
    #    ./downloadSpigot.sh
```

**Describe the bug**
Running the above CI sequence fails because it cannot find `SpraxDev/Action-Spigot@v1`. The following log is produced using the above workflow:

```
Current runner version: '2.274.2'
Operating System
  Ubuntu
  18.04.5
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20201115.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20201115.1/images/linux/Ubuntu1804-README.md
Prepare workflow directory
Prepare all required actions
Getting action download info
Failed to resolve action download info. Error: Unable to resolve action `SpraxDev/Action-Spigot@v1`, repository not found
Retrying in 13.686 seconds
Failed to resolve action download info. Error: Unable to resolve action `SpraxDev/Action-Spigot@v1`, repository not found
Retrying in 14.176 seconds
Error: Unable to resolve action `SpraxDev/Action-Spigot@v1`, repository not found
```

**To Reproduce**
1. Run the above build `.yml` file

**Screenshots, Videos, Logs or Errors**
- https://github.com/JorelAli/SpigotBuildToolsTest/runs/1439483974

-----

Totally unrelated, but this project sounds like exactly what I've been looking for for a good 4-5 months or so. I too have a project that uses NMS calls instead of reflection which requires 10 different versions of Spigot to be present in the local Maven repository to just compile the project, and I too have discovered that it takes 30+ minutes to just install those versions! This project looks very exciting and I'd love to get it working on a GitHub build system at some point!
